//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFModernVerticalMenu
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public History()
        {
            this.Employee = new HashSet<Employee>();
        }
    
        public int Id { get; set; }
        public string Item { get; set; }
    
        public virtual ICollection<Employee> Employee { get; set; }
        private static History _item;
        public static History CreateHistory()
        {
            _item = new History
            {

            };
            return _item;
        }
    }
}
